# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa12ec566eb1943dcf261c27168e7ed96a0faf71a56aea2542ce9f20e0d82a3ce26a71dd9257ce6dd2af9564567b0688046d5a8f8d0a0cef0a6f866dff7404f5

test:
  secret_key_base: 11bbab4f60b60b56affe5156a2de3aa90e293ec4dd7a0b339547a7762b143107bd30c839e9055d9e165dba5f11ff24e1654f2bb9f4bc7552b6ca5cb101553f71

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
